### PR TITLE
fix: PEP8 compliance issues

### PR DESCRIPTION
**Pull request by liewhnic**
Ypaf was firstly applied in order to atomatically fix PEP8
compliance issues. Done yapf edditing, later changes are
meant to comply flake8 statements.
Some lines were commented since they were unused.

### CODE REVIEW

**Review by degv364 — DISMISSED** [review]
Please apply futurize , as specified here: https://wiki.arcoslab.org/doku.php?id=tutorials:python_development_standards

**Comment by jprltsnz** [comment]
@degv364 formatting is othrogonal to the python 3 migration, it is fine if this is just format changes

**Comment by degv364** [comment]
As @jcrono said, if this are just formatting changes, there is no problem to merge. But take into consideration that this changes are not going to close any of the internal tasks of the python3 migration issue. I will dismiss my review.

**Review by jprltsnz — CHANGES_REQUESTED** [review]
There is still a flake8 error: `__init__.py:3:1: F401 'pyrovito_utils' imported but unused`

Please add something like this to `__init__.py`:
```python
__all__ = ['pyrovito_utils']
```

This should clear that up, see https://docs.python.org/3.6/tutorial/modules.html for more info.

**Comment by liewhnic** [comment]
`__init__.py` edited. 

@jcrono, for structured and normalized procedure might be better to change structure in https://wiki.arcoslab.org/doku.php?id=tutorials:python_development_standards, so we avoid disorder in workflow.

**Review by jprltsnz — APPROVED** [review]

**Pull request merged**
